### ISSUE TITLE
Marketplace Offer prüfen/anpassen

### ISSUE THREAD

**Issue by dariobro** [whiteducksoftware/azure-devops-build-agent#14]
- [x] Neues Offering einstellen (Zwei Pläne: Build Agent scalable (Linux) / Build Agent Single Windows VM)
- [x] Alte Offerings raus nehmen, wenn die LandingPage aktuell ist!

**Comment by dariobro** [comment]
### Fehlt: 

**Offer listing**
- [ ] richtiges Logo?
- [ ] Screenshots

**Preview audience**
- [ ] weitere Subscriptions?

**Technikal configuration**
- [ ] alles

**Plan overview -> Pricing and availability**
- [ ] Supportanfrage für Preisänderung

**Comment by nmeisenzahl** [comment]
Bitte nutzt die finalen Texte (oder Teile davon auch und das Logo auch im README.md im Repo.

**Comment by nmeisenzahl** [comment]
Aktueller Stand 2022:

- [ ] Aktuelles Offering (Offer id: wd-azure-devops-build-agent) prüfen
  - Hier gab es ein Problem bei der Auswahl des Plans (Linux/Win) in Offering -> Ist das noch so?
  - Offering Texte validieren/anpassen
  - Test-deployment durchführen
- [ ] Wenn alles passt alte Offerings offline nehmen/löschen

**Comment by ndeeH** [comment]
- [ ] Community: Yammer durch GitHub Community ablösen
- [ ] Scalable Agent Live schalten
- [ ] Homepage Links auf Scalable ändern @msuemmchen 
- [ ] Landing-Page anpassen auf Scalable BuildAgent
