### ISSUE TITLE
Test container job for arm architecture build

### ISSUE THREAD

**Issue by dariobro** [whiteducksoftware/azure-devops-build-agent#28]

**Comment by nmeisenzahl** [comment]
@msuemmchen Christian baut aktuell nichts auf ARM. Ich wollte da jetzt nicht mit was reingrätschen. Kannst du da bei Gelegenheit mein eine kleine Demo App einplanen? /cc @dariobro

**Comment by nmeisenzahl** [comment]
Due to limitations in the Azure DevOps Docker and Container task, this will not be part of v1.0.

We might need to think about using the Bash task or build our own task based on buildx or buildkit cli for building ARM-based container images. same for running them.

Requirs #39 
/cc @dariobro
