### ISSUE TITLE
Update to Docker Engine 20.10 & further improvements

### ISSUE THREAD

**Issue by nmeisenzahl** [whiteducksoftware/azure-devops-build-agent#34]
1. Updating to Docker Engine 20.10 will bring us many improvements due to the GA of BuildKit. This includes:
* Faster build times
* multi-arch support

2. We should also verify our deployment to make sure it matches all best practices we learned of the time:
* lifecycle of local images (disk space)
* proper disk size & partition layout for Docker as well as the Agent itself 

3. We could configure a registry mirror to help our customers with the Docker Hub limits

**Comment by nmeisenzahl** [comment]
With Docker Engine 20.10 we should be able to remove all previous QEMU integration because it is included by default. More details: https://www.docker.com/blog/multi-arch-images/

**Comment by nmeisenzahl** [comment]
BuildKit itself brings lots of improvements ([more details](https://www2.slideshare.net/nmeisenzahl/die-evolution-von-container-image-builds-239908168)) in the build process itself. It also supports to cache image layers into an external image registry which helps to lower build times with multiple build machines (machine 1 builds a layer and pushes it into the registry where machine 2 can reuse it.)

**Comment by nmeisenzahl** [comment]
open for discussions @dariobro @mjisaak @msuemmchen

**Comment by nmeisenzahl** [comment]
The Google mirror would be a good choice for a registry mirror. [more details](https://cloud.google.com/container-registry/docs/pulling-cached-images). We need to verify whether this is limited to GCP users only (I don't think so).

**Comment by dariobro** [comment]
> 1. We should also verify our deployment to make sure it matches all best practices we learned of the time:
> 
> * lifecycle of local images (disk space)
> * proper disk size & partition layout for Docker as well as the Agent itself

The build agent should be targeting smaller and highly frequent build scenarios. Since the VMs are removed after a specific time, we should just consider the OS disk to be "big enough".

**Comment by nmeisenzahl** [comment]
@dariobro and I decided that we will skip 2) and 3) for this first version
